export const initialBoard = [
    [
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♖",
            color: "white",
            type: "rook",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♘",
            color: "white",
            type: "knight",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♗",
            color: "white",
            type: "bishop",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♕",
            color: "white",
            type: "queen",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♔",
            color: "white",
            type: "king",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♗",
            color: "white",
            type: "bishop",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♘",
            color: "white",
            type: "knight",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♖",
            color: "white",
            type: "rook",
        },
    ],
    [
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♙",
            color: "white",
            type: "pawn",
        },
    ],
    [
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
    ],
    [
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
    ],
    [
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
    ],
    [
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
        { possibleMoves: [], isEmpty: true },
    ],
    [
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♟︎",
            color: "black",
            type: "pawn",
        },
    ],
    [
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♜",
            color: "black",
            type: "rook",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♞",
            color: "black",
            type: "knight",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♝",
            color: "black",
            type: "bishop",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♛",
            color: "black",
            type: "queen",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♚",
            color: "black",
            type: "king",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♝",
            color: "black",
            type: "bishop",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♞",
            color: "black",
            type: "knight",
        },
        {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♜",
            color: "black",
            type: "rook",
        },
    ],
];

export const promotionSelections = {
    queen: {
        black: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♛",
            color: "black",
            type: "queen",
        },
        white: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♕",
            color: "white",
            type: "queen",
        },
    },
    rook: {
        black: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♜",
            color: "black",
            type: "rook",
        },
        white: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♖",
            color: "white",
            type: "rook",
        },
    },
    bishop: {
        black: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♝",
            color: "black",
            type: "bishop",
        },
        white: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♗",
            color: "white",
            type: "bishop",
        },
    },
    knight: {
        black: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♞",
            color: "black",
            type: "knight",
        },
        white: {
            possibleMoves: [],
            isEmpty: false,
            moved: false,
            symbol: "♘",
            color: "white",
            type: "knight",
        },
    },
};
